base_template.error.no_manage = Your controller is not capable of \
    managing templates, cannot list templates used.
base_template.info.package = Package
base_template.info.name = Name
base_template.info.template = Template
base_template.info.update = Last Update
base_template.form.title_new = Create a New Template
base_template.form.title_update = Edit Template [_1]
base_template.form.package_info = <br>If blank, becomes global template
base_template.list.page_title = Template Listing By Package
base_template.list.title = Browse Templates
base_template.list.global = Global Templates
base_template.list.none_in_package = No templates in package
base_template.toolbox.label.create = <a href="[_1]">Create a new template</a>
base_template.toolbox.label.edit = <a href="[_1]">Edit template</a>
base_template.toolbox.label.remove = <a href="[_1]">Remove template</a>
base_template.usedbox.global = Global
base_template.error.does_not_exist = Template '[_1]' does not exist.
base_template.error.fetch_all = Failed to fetch templates in package '[_1]': [_2]
base_template.error.fetch_global = Failed to get global templates: [_1]
base_template.error.fetch = Failed to fetch template '[_1]': [_2]
base_template.error.update = Failed to update template: [_1]
base_template.error.create_exists = Template '[_1]' already exists, cannot create.
base_template.error.create = Failed to create template '[_1]': [_2]
base_template.error.remove = Error removing template '[_1]': [_2]
base_template.status.update = Template '[_1]' updated ok
base_template.status.create = Template '[_1]' created ok
base_template.status.remove = Template '[_1]' removed ok
