obj_activity.info.date = Activity On
obj_activity.info.date_range = Activity Between
obj_activity.info.action = Action
obj_activity.info.type = Object Type
obj_activity.info.id = Object ID
obj_activity.info.title = Title
obj_activity.info.user = Activity By
obj_activity.search_form.title = Search for Object Activity Records
obj_activity.search_form.summary = Enter criteria below to search the object \
    activity logs. The more criteria you enter, the more restrictive your \
    search and the fewer results you will retrieve.
obj_activity.search_form.actions_first = Actions...
obj_activity.search_form.types_first = Types...
obj_activity.search_results.title = Object Activity Search Results
obj_activity.search_results.none = There were no records found matching your criteria.
obj_activity.search_results.some = Following are the results matching your \
    search of object activity.