base_group.detail.page_title = Group [_1] details
base_group.detail.edit_record = <a href="[_1]">Edit</a> this record
base_group.detail.title = Group Detail
base_group.info.label.name = Group Name 
base_group.info.label.notes  = Notes
base_group.info.label.members = Members
base_group.detail.no_members = This group has no members.
base_group.form.title.new = Create a New Group
base_group.form.title.update = Edit Group [_1]
base_group.form.remove_record = <a href="[_1]"><b>Remove</b></a> this group
base_group.form.label.assign_users = Assign Users
base_group.form.label.pop_select = &quot;[_1]&quot; Users
base_group.form.label.member_select = Members
base_group.list.title = Group Listing
base_group.list.summary = Listed below are all the groups currently in the system.
base_group.list.no_groups = There are currently no groups in the system that \
    you have security access to view.
base_group.error.failed_fetch = Failed to retrieve groups: [_1]
base_group.error.failed_member_fetch = Failed to retrieve all users: [_1]
base_group.error.failed_member_remove = Failed to remove user members: [_1]
base_group.error.failed_member_add = Failed to add user members: [_1]
base_group.status.update_ok = Group membership information updated: added [_1]; removed [_2].
