# Contact: Salve J. Nilsen <salvejn@met.no>
base_group.detail.page_title = Detaljer for gruppe [_1]
base_group.detail.edit_record = <a href="[_1]">Endre</a> denne oppf&oslash;rigen
base_group.detail.title = Detaljer om gruppe
base_group.info.label.name = Navn
base_group.info.label.notes  = Beskrivelse
base_group.info.label.members = Medlemmer
base_group.detail.no_members = Denne gruppen har ingen medlemmer
base_group.form.title.new = Opprett en ny gruppe
base_group.form.title.update = Redig&eacute;r gruppen [_1]
base_group.form.remove_record = <a href="[_1]"><b>Fjern</b></a> denne gruppen
base_group.form.label.assign_users = Finn medlemmer
base_group.form.label.pop_select = &quot;[_1]&quot; medlemmer
base_group.form.label.member_select = Medlemmer
base_group.list.title = Liste over grupper
base_group.list.summary = F&aring;lgende grupper er for tiden registrert.
base_group.list.no_groups = For tiden er det ingen grupper registrert, som du \
    har rettigheter til &sring; se p&aring;.
base_group.error.failed_member_fetch = Klarte ikke &aring; hente medlemmer: [_1]
base_group.error.failed_member_remove = Klarte ikke &aring; fjerne medlem: [_1]
base_group.error.failed_member_add = Klarte ikke &aring; legge til medlem: [_1]
base_group.status.update_ok = Gruppemedlemsskap oppdatert: la til [_1]; fjernet [_2].

