news.info.title = Title
news.info.img_src = Image Source
news.info.img_url = Image URL
news.info.img_align= Image Align
news.info.section = Section
news.info.content = Content
news.info.posted_on = Posted On
news.info.date = Date
news.info.active_on = Active On
news.info.expires_on = Expires On
news.detail.page_title = News: [_1]
news.detail.title = News Detail
news.detail.main_link = Main
news.detail.edit_link = <a href="[_1]">Edit</a> this record</a>
news.detail.comments = Comments
news.filter.by_section = By section
news.filter.first_section = ---All Sections---
news.filter.by_date = By date
news.filter.date_info = (picking month + year is ok)
news.form.title_update = Edit News: [_1]
news.form.title_create = Create News
news.home.title = News Home
news.home.summary = The latest [_1] news entries are included below. To \
    view other entries, use the form above.

# next two are old + not used in templates anymore, keep for compat
news.item.posted_date = Posted on [_1]
news.item.posted_by = by <a href="[_1]">[_2]</a>

news.item.posted_user_and_date = <a href="[_1]">[_2]</a> on [_3]
news.item.posted_on_date = on [_1]
news.item.edit = Edit
news.item.permalink = Permanent

news.list.title = News Entries
news.list.count = Active news stories: [_1]
news.list.filtered_by = Filtered by:
news.list.nothing = nothing
news.edit_list.title = Edit Many News Items
news.edit_list.summary = Be sure of your edits, since you will be modifying many records at once.
news.edit_list.edit = Edit?
news.search.page_title = Search for News Items
news.box.home = News home
news.box.edit = Edit news item
news.box.remove = Remove news item
news.box.create = Create a new news story
news.box.edit_section = Edit news sections

news.error.fetch          = Failed to fetch news object '[_1]': [_2]
news.error.save           = Failed to save news object '[_1]': [_2]
news.error.fetch_multiple = Failed to fetch news items: [_1]
news.error.fetch_sections = Failed to get news sections: [_1]
news.error.archive_date   = You must provide at least a month and year to browse the archive.
news.error.db_unsupported = This database ([_1]) not supported for extracting date information.

news.status.multi_updates = Attempted: [_1]; successful updates [_2]