wiki.preview = Preview
wiki.save = Save
wiki.search = Search
wiki.view = View
wiki.version = Version:
wiki.other_versions = Other versions:
wiki.no_other_versions = no previous versions

wiki.link_home = Home
wiki.link_all_pages = All Pages
wiki.link_recent = Recent Changes
wiki.link_references = Referenced By

wiki.no_nodes = No pages

wiki.all_nodes_title = All Pages

wiki.recent_nodes_title = Recently Changed Pages

wiki.referenced_by_title = List Referencing Pages
wiki.nodes_referencing = The following pages reference [[_0]]

wiki.search_results_title = Search Results
wiki.search_results_summary = The following pages match [_0]

wiki.edit_title = Editing Page [_0]

wiki.preview_title = Previewing Page [_0]
