# Contact: Chris Winters <chris@cwinters.com>
base_user.new_complete.page_title = Account Created!
base_user.new_complete.title = E-Mail Sent
base_user.new_complete.summary = Your account information has been sent to \
    <tt>[_1]</tt>. Follow the instructions to login and activate your account.
base_user.new_form.page_title = Create a User Account
base_user.new_form.howto_intro = Creating a new account is easy! We only need two things:
base_user.new_form.howto_login = the login you'd like to use
base_user.new_form.howto_email = working email address
base_user.new_form.instructions = Once you fill out these items below and the \
    username is not already taken, you'll be emailed your username and a \
    system-generated password. You can then login using the password \
    sent to you. Once logged in, you can change your password to \
    whatever you like.
base_user.new_form.label.login = Desired Login
base_user.new_form.label.email = Working email address
base_user.detail.page_title = User Information
base_user.detail.edit_link = <a href="[_1]">Edit</a> this record
base_user.detail.title = User Detail
base_user.detail.label.member = Member of Groups
base_user.info.name = Full Name
base_user.info.first_name = First Name
base_user.info.last_name = Last Name
base_user.info.email = E-Mail
base_user.info.login = Login Name
base_user.info.password = Password
base_user.info.language = Language
base_user.info.title = Title
base_user.info.notes = Notes
base_user.form.title_new = Create New User Account
base_user.form.title_update = Edit User Account [_1]
base_user.form.remove_link = <a href="[_1]">Remove</a> this record
base_user.form.password_change = If you do not type anything, the password will not be changed.
base_user.search_form.title = Search for Users
base_user.search_results.title = User Search Results
base_user.search_results.no_match = No users matched criteria.

base_user.password_info.title = Get Information to Retrieve Password
base_user.password_info.summary = Enter your login or email address and I'll email you a new password.
base_user.password_info.login = Login name
base_user.password_info.email = E-mail address
base_user.password_info.send = Send Password

base_user.password_sent.title = Sent New Password
base_user.password_sent.summary = A new password has been emailed to '[_1]'; please \
    check your inbox and use the password there to login. Once you login you should \
    probably change your password as well.

base_user.password_mail.subject = Password change for [_1]

base_user.new_mail.subject = Account information for [_1]
base_user.new.mail_failure = Could not send email to you with generated password: [_1]. \
    However, your account was created. Try the 'Forgot password' feature later to get \
    your password changed and sent to you.

base_user.new.name_in_use = The username you requested is already in use; please try another.
base_user.new.duplicate_email = The email address you supplied is already in use.
base_user.new.no_login = You cannot create an account without entering a login!
base_user.new.invalid_email = The email address you entered is invalid.
base_user.new.no_mailcheck_module = Insufficient modules to check email validity.
base_user.new.create_failure = Failed to create your record: [_1]
base_user.new.security_failure = Error setting security information on your record: [_1]

base_user.user.search_error = Error running search: [_1]
base_user.user.group_fetch_fail = Failed to fetch user's groups: [_1]
base_user.user.lang_fetch_fail = Failed to fetch languages: [_1]
base_user.user.password_mismatch = Passwords do not match. Please re-enter.
base_user.user.password_changed = Password changed.
base_user.user.group_add_fail = Record created but group membership wrong.
base_user.user.group_add_ok = User added to 'public' group

base_user.password.enter_one = You must specify either a login name or an email address.
base_user.password.fetch_fail = Error fetching user objects with your information: [_1]
base_user.password.no_user = No user exists with this information. Try again.
base_user.password.save_fail = Failed to save user object with new password. Error: [_1]
base_user.password.mail_fail = Failed to send email with your new password. Error: [_1]
base_user.password.save_existing_fail = Failed to reset your password to previous value \
    after failing to send email (Error: [_1]). You may need to contact an administrator \
    ([_2]) to reset your password.
base_user.password.mail_ok = Mail sent ok to address '[_1]'.