# Contact: Salve J. Nilsen <salvejn@met.no>
base_user.new_complete.page_title = Konto opprettet!
base_user.new_complete.title = Epost Sendt
base_user.new_complete.summary = Kontoinformasjonen din er blitt sendt til \
    <tt>[_1]</tt>. F&oslash;lg instruksjonene der for &aring; logge deg inn \
    og aktivisere kontoen din.
base_user.new_form.page_title = Opprett brukerkonto
base_user.new_form.howto_intro = Oppretting av en ny konto er enkelt! Vi \
    trenger kun to ting:
base_user.new_form.howto_login = Brukernavnet du &oslash;nsker &aring; ha
base_user.new_form.howto_email = En fungerende epostadresse
base_user.new_form.instructions = Etter du har fylt ut informasjonen \
    nedenfor og vi har sjekket at brukernavnet ditt ikke allerede er \
    i bruk, s&aring; sender vi deg et ebrev med innloggingsinformasjon og \
    et systemgenerert passord. Du kan s&aring; logge deg inn med dette \
    passordet og eventuelt endre dette til noe du selv kan huske.
base_user.new_form.label.login = &Oslash;nsket brukernavn
base_user.new_form.label.email = Fungerende epostadresse
base_user.detail.page_title = Brukerinformasjon
base_user.detail.edit_link = <a href="[_1]">Endre</a> denne siden
base_user.detail.title = Brukerdetaljer
base_user.detail.label.member = Medlem i grupper
base_user.info.name = Fullt navn
base_user.info.first_name = Fornavn
base_user.info.last_name = Etternavn
base_user.info.email = Epost
base_user.info.login = Brukernavn
base_user.info.password = Passord
base_user.info.language = Spr&aring;k
base_user.info.title =  Tittel
base_user.info.notes = Notater
base_user.info.image = Bilde
base_user.info.location = Tilholdssted
base_user.info.description = Jobb-beskrivelse
base_user.info.phone = Telefonnummer
base_user.form.title_new = Opprett ny brukerkonto
base_user.form.title_update = Endre brukerkonto for [_1]
base_user.form.remove_link = <a href="[_1]">Fjern</a> denne kontoen
base_user.form.password_change = Hvis du ikke skriver noe vil passordet \
    ikke endres.
base_user.search_form.title = S&oslash;k etter folk
base_user.search_results.title = S&oslash;keresultat
base_user.search_results.no_match = Ingen treff med gitte s&oslash;kekriterier

base_user.password_info.title = F&aring; tildelt nytt passord
base_user.password_info.summary = Skriv ditt brukernavn eller din \
    epostadresse, s&aring; skal jeg sende deg et nytt passord.
base_user.password_info.login = Brukernavn
base_user.password_info.email = Epostadresse
base_user.password_info.send = Send Passord

base_user.password_sent.title = Nytt password er sendt
base_user.password_sent.summary = Et nytt passord er blitt sendt til '[_1]'; \
	Vennligst sjekk epostboksen din og benytt det nye passordet for &aring; \
    logge deg inn igjen. N&aring;r du er inne b&oslash;r du ogs&aring; \
    bytte ditt passord.
base_user.password_mail.subject = Passordbytte for [_1]

base_user.new_mail.subject = Kontoinformasjon for [_1]
base_user.new.mail_failure = Kunne ikke sende epost til deg med nytt passord: [_1]

base_user.new.name_in_use = Brukernavnet du ba om er allerede i bruk; Vennligst pr&oslash;v et annet.
base_user.new.duplicate_email = Epostadressen du oppga er allerede i bruk.
base_user.new.no_login = Din konto kan ikke opprettes uten at du oppgir et \
    brukernavn!
base_user.new.invalid_email = Epostadressen du oppga er ikke gyldig!
base_user.new.no_mailcheck_module = Kan ikke sjekke epostadressens gyldighet.
base_user.new.create_failure = Kan ikke opprette ny bruker: [_1]
base_user.new.security_failure = Kan ikke sette sikkerhetsniv&aring; for ny bruker: [_1]

base_user.user.search_error = Feil i s&oslash;keoperasjon: [_1]
base_user.user.group_fetch_fail = Kunne ikke finne grupper brukeren er medlem i: [_1]
base_user.user.lang_fetch_fail = Kunne ikke finne spr&aring;oppsett: [_1]
base_user.user.password_mismatch = Passordene stemte ikke overens; Vennligst skriv de p&aring; nytt.
base_user.user.password_changed = Passord er endret.
base_user.user.group_add_fail = Bruker er opprettet, men innmelding i gruppe feilet.
base_user.user.group_add_ok = Brukeren er lagt til 'public' gruppen

base_user.password.enter_one = Vennligst oppgi enten brukernavn eller epostadresse.
base_user.password.fetch_fail = Kunne ikke finne brukere med &oslash;nskede kriterier: [_1]
base_user.password.no_user = Ingen brukere finnes med disse kriteriene. Pr&oslash;v igjen.
base_user.password.save_fail = Kunne ikke lagre nytt passord: [_1]
base_user.password.mail_fail = Kunne ikke sende epost med nytt passord: [_1]
base_user.password.save_existing_fail = Kunne ikke sette tilbake passord til \
    opprinnelig verdi etter &aring; ha feilet &aring; sende epost \
    (Error: [_1]). Kontakt din administrator ([_2]) for &aring; f&aring; \
    satt ditt passord p&aring; ny.
base_user.password.mail_ok = Epost ble sendt til adressen '[_1]'.
