sys_doc.info.system_doc = System doc
sys_doc.info.module_listing = Module listing
sys_doc.info.package_listing = Package listing
sys_doc.module.page_title = OpenInteract2 System Documentation / Module Documentation
sys_doc.module.title = Module Listing
sys_doc.module.doc_title = Display Module: [_1]
sys_doc.package.page_title = OpenInteract2 System Documentation / Package Documentation
sys_doc.package.title = OpenInteract2 Package Documentation
sys_doc.package_doc_title = Display Document from Package: [_1]
sys_doc.package.no_docs = No documentation available for this package.
sys_doc.pod.no_content = No content.
sys_doc.pod.cannot_display_module = Failed to display module: [_1]
sys_doc.menu.page_title = OpenInteract2 System Documentation / Index
sys_doc.menu.title = OpenInteract2 System Documentation
sys_doc.menu.starting = Good places to start out for OpenInteract and SPOPS are \
    the POD manuals shipped with the distributions. See \
    <a href="[_1]">OpenInteract2::Manual</a> and <a href="[_2]">SPOPS::Manual</a>. \
    A look through the <a href="[_3]">Template::Manual</a> might also be \
    worth your time.
sys_doc.menu.package = <a href="[_1]">View Package Documentation</a>: This \
    allows you to browse the documentation that comes with each package. \
    (For website developers and package authors.)
sys_doc.menu.module = <a href="[_1]">View Perl Module Documentation</a>: This \
    allows you to browse the different modules making up SPOPS and \
    OpenInteract along with all the modules used by them. This includes \
    the SPOPS and OpenInteract manuals. (Mostly for Perl developers.)
sys_doc.error.pod_viewer = Failed to load POD viewer: [_1]
sys_doc.error.pod_parse = Error parsing POD: [_1]
sys_doc.error.cannot_find_package_doc = Cannot find package documentation: [_1]
sys_doc.error.cannot_find_module_doc = Cannot find module: [_1]
sys_doc.error.cannot_open_file = Error opening file '[_1]': [_2]