comments.posting = Posted by [_1] on [_2]
comments.detail.title = Comment Detail
comments.no_comment = No comment to display.
comments.no_comments = No comments to display.
comments.recent      = Recent Comments

comments.form.title = Post a comment
comments.form.no_html = (No HTML; '&lt;ecode&gt;&lt;/ecode&gt;' preformats; http:// autocreates links.)
comments.form.remember = Remember info?
comments.form.notify = Email on new thread posts?
comments.form.notify_yes_sub   = Yes, keep subscription
comments.form.notify_yes_unsub = No, unsubscribe
comments.form.notify_no_sub    = Yes, subscribe to thread
comments.form.notify_no_unsub  = No, do not subscribe to thread
comments.form.preview = Preview
comments.form.post = Post
comments.form_page.title = Comments
comments.form_page.title_preview = Preview

comments.info.name = Name
comments.info.email = E-Mail
comments.info.url = URL
comments.info.subject = Subject
comments.info.comments = Comments
comments.info.poster = Poster
comments.info.count = #
comments.info.date = Date
comments.info.thread = Thread
comments.info.object = Comments on: [_1]
comments.info.unknown_object = an unknown object.

comments.list_page.title = Comments
comments.list_page.overview = Latest comments from [_1] to [_2] out of [_3].
comments.list_page.previous_link = Previous
comments.list_page.next_link = Next
comments.list_page.no_comments = No comments available.

comments.notify_list.title = Comment Notifications
comments.notify_list.summary_thread = The following people have been asked to be notified \
    for the thread [_1].
comments.notify_list.summary_no_thread = The following people have been asked to be notified \
    for a thread I cannot determine.
comments.notify_list.no_notifications = Nobody has asked to be notified.

comments.summary.error = Error summarizing comments
comments.summary = <a href="[_1]">Comments? ([_2])</a>
comments.notify.new_comment = A new comment has been posted on [_1]

comments.disabled = New comments are disabled.

comments.disable_list.title       = Disabled Comment Threads
comments.disable_list.no_disabled = No objects or object classes have been disabled.
comments.disable.disable          = Disable
comments.disable.enable           = Enable
comments.disable.date             = Disable Date
comments.disable.class            = Class
comments.disable.id               = Object ID
comments.disable.title            = Title
comments.disable.form_title       = Disable a Thread
comments.disable.form_summary     = Specify an object for which I should disable comments. \
    If you leave the 'Object ID' blank all objects of the specified class will have them disabled.
comments.error.disable_no_class   = You must provide a class for which I should disable comments.
comments.error.add_disable        = Failed to disable: [_1]
comments.status.add_disable_ok    = Disabled comments on class [_1] with ID [_2].
comments.error.remove_disable_no_class = You must provide a class for which I should enable comments.
comments.error.remove_disable          = Failed to remove disable on comments: [_1]
comments.status.remove_disable_ok      = Removed disable for comments on class [_1] with ID [_2].


comments.status.add_ok = Comment successfully added.
comments.status.add_notify_ok = Your notification for this thread added successfully.
comments.status.remove_notify_ok = Your notification for this thread removed successfully.

comments.error.data_missing = Data are required for the following fields: [_1]
comments.error.cannot_fetch = Error fetching comment: [_1]
comments.error.cannot_fetch_listing = Failed to fetch comments: [_1]
comments.error.cannot_fetch_by_object = Failed to fetch comments for object: [_1]
comments.error.not_found = No comment found for specified ID.
comments.error.no_id = Cannot display comment without a comment ID.
comments.error.cannot_fetch_object = Cannot fetch object to which comment is attached: [_1]
comments.error.no_class_for_object = Cannot fetch object to which comment is attached: no class specified in comment.
comments.error.cannot_add = Error adding comment: [_1]
comments.error.cannot_fetch_notify = Failed to fetch notifications: [_1]
comments.error.cannot_fetch_recent = Failed to get recent comments: [_1]
comments.error.summary_data_missing = No object or class/ID given for which to fetch a summary.
comments.error.list_for_object_data_missing = Insufficient data supplied to fetch comments by object.
comments.error.cannot_fetch_object_for_listing = Failed to fetch object with supplied information. Error logged.
comments.error.cannot_add_notify_no_email = Could not add notification since you did not give me your email address. Sorry.
comments.error.cannot_add_notify_bad_email = Could not add notification since the email address you gave ([_1]) seems to be invalid. Sorry.
comments.error.cannot_add_notify_error_dupe_check = Failed to fetch existing notifications for dupe check, so I could not add yours.
comments.error.cannot_add_notify_is_dupe = Did not add a notification to this thread since one already exists for the given email address.
comments.error.cannot_remove_notify = Failed to remove your notification for this thread: [_1]
comments.error.cannot_add_notify_persist = Your notification entry addition failed, sorry. ([_1])
