whats_new.form.title_update = Update a New Item
whats_new.form.title_new = Create a New Item
whats_new.form.remove_link = <a href="[_1]">Remove</a> this item
whats_new.info.type = Type
whats_new.info.url = URL
whats_new.info.posted_on = Posted On
whats_new.info.class = Class
whats_new.info.object_id = Object ID
whats_new.info.active = Active?
whats_new.info.description = Description
whats_new.results.title = What's New?
whats_new.results.none = Nothing is new.
whats_new.error.fetch_multiple = Cannot fetch new items: [_1]