base_error.home.title         = Recent Errors
base_error.home.summary       = Most recent [_1] from the last [_2] days.
base_error.home.by_month      = Errors by month:
base_error.home.num_days_back = Days back:
base_error.home.num_errors    = Errors:
base_error.home.num_months    = Months back:

base_error.time          = Error Time
base_error.category      = Category
base_error.message       = Message
base_error.location      = Location
base_error.host          = Host
base_error.user          = User
base_error.session       = Session ID
base_error.url           = URL Requested
base_error.browser       = User Agent
base_error.referer       = Referring URL

base_error.detail.title = Error Detail

base_error.monthly.title = Error Counts for [_1]/[_2]
base_error.monthly.by_day = Errors by day for [_1]/[_2]:

base_error.daily.title   = Errors for [_1]/[_2]/[_3]
base_error.daily.summary = There were [_4] errors on [_1]/[_2]/[_3]:

base_error.no_errors        = No errors found.
base_error.removed_files_ok = Removed [quant, _1, error] ok.

base_error.display_no_date  = No parameter 'date_id' given to display an error.
base_error.display_no_error = No error found with given date ID '[_1]'.
base_error.by_day.invalid_date = Cannot lookup errors by day - invalid date specification ([_1]). Should be in 'yyyy-mm-dd' format.
base_error.by_month.invalid_date = Cannot lookup errors by month - invalid date specification ([_1]). Should be in 'yyyy-mm' format.