full_text.search_results.title = Search Results
full_text.search.results.no_results = Your search did not find anything.
full_text.search_results.total_hits = Total hits
full_text.search.results.type = Type
full_text.search.results.description = Description

fulltext.no_keywords_title = No Keywords
fulltext.no_keywords = You did not give me any keywords to search, so I did not run a search. Please try again.
fulltext.results_save_fail = Failed to save search results: [_1]