lookup.classes.page_title = List Available Lookups
lookup.classes.title = Lookup Classes
lookup.classes.none_defined = You have not defined any lookup items in this site.
lookup.classes.summary = Following are all lookup types the system knows about. \
    Click on <tt>List items</tt> to view and edit entries.
lookup.classes.list_link = <a href="[_1]">List items</a>
lookup.field.select_first = Choose an entry
lookup.listing.page_title = Edit Lookup Entries
lookup.listing.title = Lookups: [_1]
lookup.listing.summary = Following are all entries in the lookup table under <b>[_1]</b> 
lookup.listing.summary_partition = where the values of <b>[_1]</b> are <b>[_2]</b>
lookup.listing.new_entries = New Entries
lookup.listing.remove = Remove?
lookup.listing.id = ID
lookup.partition.title = Lookup Partitions for [_1]
lookup.partition.summary = Following are all values for the field <b>[_1]</b>. \
    Choose one to edit objects that have that field's value.
lookup.partition.values = Values
lookup.error.no_partition_value = Cannot use '[_1]' as partitioned -- no value for \
    'partition_field' specified in action config.
lookup.error.fetch_partition_values = Could not retrieve values for '[_1]': [_2]
lookup.error.fetch_lookup_values = Failed to fetch lookup values: [_1]
lookup.error.fetch_lookup_related = Cannot lookup related '[_1]': [_2]
lookup.error.save = Error saving '[_1]': [_2]
lookup.error.no_lookup_type = Cannot list lookup entries without a lookup type.
lookup.error.invalid_lookup_type = Cannot list lookup entries because '[_1] is not a valid lookup.
lookup.status.save = Stored '[_1]' ([_2]) ok

