# Messages for the 'base_box' package: English
admin_tools_box.title = Admin Tools
admin_tools_box.error_browser =  <a href="[_1]">Error Browser</a>
admin_tools_box.group = Group (<a href="[_1]">List</a> |  <a href="[_2]">New</a>)
admin_tools_box.lookup = <a href="[_1]">Lookup Tables</a>
admin_tools_box.activity = <a href="[_1]">Object Activity</a>
admin_tools_box.page = <a href="[_1]">Page actions</a>
admin_tools_box.security = <a href="[_1]">Security</a>
admin_tools_box.template = Template (<a href="[_1]">List</a> | <a href="[_2]">New</a>)
admin_tools_box.doc = <a href="[_1]">System documentation</a>
admin_tools_box.theme = Theme (<a href="[_1]">List</a> | <a href="[_2]">New</a>)
admin_tools_box.user = User (<a href="[_1]">Search</a> | <a href="[_2]">New</a>)
login_box.no_account = No account? <a href="[_1]">Create one!</a>
login_box.name = Name
login_box.password = Password
login_box.remember = Remember me
login_box.forgot = Forgot password?
login_box.button.login = Login
login_box.title = Login
object_modify_box.edit_security = Edit object security
object_modify_box.edit_topics = Edit object topics
object_modify_box.summary = No actions for you to take on this object.
object_modify_box.not_entered = Since this object has not yet been entered in the system, \
     you cannot edit its properties.
object_modify_box.cannot_view = Cannot view actions.
object_modify_box.title = Object info
powered_by_box.summary = This website is powered by the following technologies:
powered_by_box.title = Powered By
user_info_box.customize = Customize
user_info_box.signout = Sign Out
user_info_box.no_login = You are not logged in
user_info_box.title = Your Info
