# Messages for the 'base_box' package: Norwegian
admin_tools_box.error_browser = <a href="[_1]">Feil-logg</a>
admin_tools_box.group = Grupper (<a href="[_1]">Vis alle</a> | <a href="[_2]">Lag ny</a>)
admin_tools_box.lookup = <a href="[_1]">Liste over tabeller</a>
admin_tools_box.activity = <a href="[_1]">Aktivitetslogg</a>
admin_tools_box.page = <a href="[_1]">Sideadministrasjon</a>
admin_tools_box.security = <a href="[_1]">Tilgangskontroll</a>
admin_tools_box.template = Side-maler (<a href="[_1]">Vis alle</a> | <a href="[_2]">Lag ny</a>)
admin_tools_box.doc = <a href="[_1]">Systemdokumentasjon</a>
admin_tools_box.theme = Fargeprofiler (<a href="[_1]">Vis alle</a> | <a href="[_2]">Lag ny</a>)
admin_tools_box.user = Brukere (<a href="[_1]">S&oslash;k</a> | <a href="[_2]">Lag ny</a>)
admin_tools_box.title = Administrasjons-verkt&oslash;y
login_box.no_account = Ingen konto? <a href="[_1]">Lag en ny!</a>
login_box.name = Brukernavn
login_box.password = Passord
login_box.remember = Ikke sp&oslash;r om passord fra n&aring; av
login_box.forgot = Glemt passord?
login_box.button.login = Logg inn
login_box.title = Logg inn
object_modify_box.edit_security = Endre sikkerhetsniv&aring;
object_modify_box.edit_topics = Endre titler
object_modify_box.summary = Ingen operasjoner tillatt.
object_modify_box.not_entered = Siden dette objektet ikke enda er lagt til \
     i systemet, kan du ikke endre p&aring; dets egenskaper.
object_modify_box.cannot_view = Visning av operasjoner er ikke tillatt.
object_modify_box.title = Objektinformasjon
powered_by_box.summary = Dette nettstedet benytter seg av f&oslash;lgende teknologier:
powered_by_box.title = Teknologiplattform
user_info_box.customize = Endre info
user_info_box.signout = Logg ut
user_info_box.no_login = Du er ikke logget inn
user_info_box.title = Info om meg
