logout.title   = Logged Out
logout.summary = You are now logged out. You can \
    <a href="[_1]">return to the system</a>.

package_detail.page_title         = Package Details
package_detail.back_listing       = <a href="[_1]">Back to listing</a>
package_detail.title              = Package Detail
package_detail.label.package      = Package: 
package_detail.label.install_date = Installed: 
package_detail.label.author       = Author(s): 
package_detail.label.website      = Website: 
package_detail.label.dependencies = Dependent on: 
package_listing.page_title        = Package Listing
package_listing.title             = Package Listing
package_listing.label.detail      = Detail
package_detail.error.no_package   = Could not find package with name '[_1]'
package_listing.summary = Listed below are all the packages installed to your \
    website. Details are available for each.

email_tester.title           = E-mail Tester
email_tester.address         = Address
email_tester.subject         = Subject
email_tester.message         = Message
email_tester.send            = Send
email_tester.default_subject = Test message from OpenInteract2
email_tester.default_message = This is a test message from OpenInteract2.
email_tester.smtp_host       = Sent messages using SMTP host '[_1]'
email_tester.send_ok         = Sent message to '[_1]' ok.
email_tester.send_error      = Error sending message to '[_1]': [_2]
 
